name: "Track Competitor Product Updates"

on:
  schedule:
    # Runs exactly once a day at 18:00 UTC (10:00 AM PST)
    - cron: '0 18 * * *'
  workflow_dispatch: # Allows manual trigger from the Actions tab

permissions:
  contents: write
  issues: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Competitor Updates
        id: webchanges
        uses: swimmwatch/webchanges-action@v1.0.1
        with:
          jobs: |
            name: SUSE Technical Release Notes
            url: https://forums.suse.com/c/announcements/12.rss
            filters:
              - html2text
            ---
            name: SUSE Rancher Releases
            url: https://github.com/rancher/rancher/releases
            filters:
              - html2text
            ---
            name: Nutanix product updates
            url: https://next.nutanix.com/product-updates
            filters:
              - html2text
            ---
            name: Broadcom VMware Cloud Foundation Releases
            url: https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-0/release-notes/
            filters:
              - html2text
            ---
            name: AWS EKS Kubernetes Version Support Notes
            url: https://github.com/aws/eks-distro
            filters:
              - html2text
            ---
            name: Azure AKS GitHub Releases
            url: https://github.com/Azure/AKS/releases
            filters:
              - html2text
            ---
            name: Google GKE Production Release Notes
            url: https://docs.cloud.google.com/kubernetes-engine/docs/release-notes
            filters:
              - html2text
